// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJGJ8HLmChCQ6k0rGjKyDsHBzxLKWzj9Y',
    appId: '1:163127191634:web:7b5ae6f8501aa74ce4d78b',
    messagingSenderId: '163127191634',
    projectId: 'quiz-application-70a95',
    authDomain: 'quiz-application-70a95.firebaseapp.com',
    storageBucket: 'quiz-application-70a95.firebasestorage.app',
    measurementId: 'G-8H96EW1SR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb38Oivy0Ey8U20PttlbESfEjcdZ0QhfY',
    appId: '1:163127191634:android:ffecbe97eb69668ee4d78b',
    messagingSenderId: '163127191634',
    projectId: 'quiz-application-70a95',
    storageBucket: 'quiz-application-70a95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtjeO2_ZhIjLnJVrjVLNt92fSg-37BuMw',
    appId: '1:163127191634:ios:1f5793c232dcbe60e4d78b',
    messagingSenderId: '163127191634',
    projectId: 'quiz-application-70a95',
    storageBucket: 'quiz-application-70a95.firebasestorage.app',
    iosBundleId: 'com.example.quizApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtjeO2_ZhIjLnJVrjVLNt92fSg-37BuMw',
    appId: '1:163127191634:ios:1f5793c232dcbe60e4d78b',
    messagingSenderId: '163127191634',
    projectId: 'quiz-application-70a95',
    storageBucket: 'quiz-application-70a95.firebasestorage.app',
    iosBundleId: 'com.example.quizApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJGJ8HLmChCQ6k0rGjKyDsHBzxLKWzj9Y',
    appId: '1:163127191634:web:1ac447d8c6ab53fee4d78b',
    messagingSenderId: '163127191634',
    projectId: 'quiz-application-70a95',
    authDomain: 'quiz-application-70a95.firebaseapp.com',
    storageBucket: 'quiz-application-70a95.firebasestorage.app',
    measurementId: 'G-76XW74R1W5',
  );
}
